project_id = "delta-wonder-443918-h2"
region     = "us-central1"
db_host    = "my-sql-instance.us-central1.c.project-id.internal"
db_user    = "root"
db_password = "your-password"
db_name    = "users"
